AWSTemplateFormatVersion: 2010-09-09
Description: EKS Addons Deployment

Parameters:
  ClusterName:
    Type: String
    Description: Enter the name of your existing EKS Cluster

Resources:
  VPCCNIAddon: 
    Type: AWS::EKS::Addon
    Properties:
      AddonName: vpc-cni
      ClusterName: !Ref ClusterName
      ResolveConflicts: OVERWRITE 

  EBSCSIDriverAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: aws-ebs-csi-driver 
      ClusterName: !Ref ClusterName

  KubeProxyAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: kube-proxy
      ClusterName: !Ref ClusterName

  CoreDNSAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: coredns
      ClusterName: !Ref ClusterName

  EKSPodIdentityAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: eks-pod-identity-agent 
      ClusterName: !Ref ClusterName

Outputs:
  VpcCniName:
    Description: Addons name 
    Value: !Ref VPCCNIAddon