AWSTemplateFormatVersion: 2010-09-09
Description: |

Parameters:
  ClusterName:
    Type: String
    Description: Enter the name of your existing EKS Cluster

  SubnetIds:
    Type: String
    Description: Enter the subnet IDs 
    
  InstanceTypes:
    Type: String
    Description: Enter the instance types 

Resources:
  EKSNodeGroup:
  Type: AWS::EKS::Nodegroup
  Properties:
    ClusterName: !Ref ClusterName
    NodegroupName: !Sub '${ClusterName}-nodegroup'
    NodeRole: arn:aws:iam::949829288387:role/EKS-WorkerNode-Role
    SubnetIds: !Split [",", !Ref SubnetIds]
    InstanceTypes:
      - !Ref InstanceTypes
    DiskSize: 20
    ScalingConfig:
      DesiredSize: 1
      MaxSize: 3
      MinSize: 1

Outputs:
  NodeGroupName:
    Description: The name of the EKS node group
    Value: !Ref EKSNodeGroup